### ISSUE TITLE
博主怎么不用Istio代替go-micro试试？

### ISSUE THREAD

**Issue by zwl1619** [wuYin/blog#2]
博主怎么不用Istio代替go-micro试试？

**Comment by wuYin** [comment]
go-micro 的官博 [micro.mu/blog](https://micro.mu/blog/) 有一份现成的 [翻译文档](http://btfak.com/page2/)，可以快速学习上手。
我初学先从容易的开始，Istio 后边再对比学习，感谢建议 😋

**Comment by littleboss** [comment]
@zwl1619 你后面有比较么？
